#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: CloudflareEdge"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Cloudflare Edge",
  "ShortName": "CloudflareEdge",
  "Capability": "CloudflareEdge",
  "LocalStore": false,
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "EntryParameters": [],
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "Properties": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  }
}'

